apiVersion: apps/v1
kind: Deployment
metadata:
  name: runlogic
  namespace: hawk
  labels:
    app: runlogic
    env: test
spec:
  selector:
    matchLabels:
      app: runlogic
      env: test
  template:
    metadata:
      labels:
        app: runlogic
        env: test
    spec:
      containers:
        - name: runlogic
          image: tibinlukose/runlogic:1.2
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: runlogic-service
  namespace: hawk
spec:
  selector:
    app: runlogic
    env: test
  ports:
    - appProtocol: http
      name: dummy
      protocol: TCP
      port: 80
      targetPort: 8080