apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts
  namespace: falcon
  labels:
    app: alerts
    env: test
spec:
  selector:
    matchLabels:
      app: alerts
      env: test
  template:
    metadata:
      labels:
        app: alerts
        env: test
    spec:
      containers:
        - name: alerts
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
          image: tibinlukose/alerts:1.7
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: alerts-service
  namespace: falcon
spec:
  selector:
    app: alerts
    env: test
  ports:
    - appProtocol: http
      name: dummy
      protocol: TCP
      port: 80
      targetPort: 8080