apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawk-server
  namespace: hawk
  labels:
    app: hawk-server
    env: test
spec:
  selector:
    matchLabels:
      app: hawk-server
      env: test
  template:
    metadata:
      labels:
        app: hawk-server
        env: test
    spec:
      containers:
        - name: hawk-server
          image: tibinlukose/hawk-server
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hawk-server-service
  namespace: hawk
spec:
  selector:
    app: hawk-server
    env: test
  ports:
    - protocol: TCP
      appProtocol: http
      name: hawk-port
      port: 8080
      targetPort: 8080