apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: logic-app
  namespace: hawk
spec:
  selector:
    matchLabels:
      app: runlogic
      env: test
  jwtRules:
  - issuer: http://192.168.3.0/auth/realms/hawk
    jwksUri: http://192.168.3.0/auth/realms/hawk/protocol/openid-connect/certs
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: logic-app
  namespace: hawk
spec:
  {}