apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-virtual-service
  namespace: hawk
spec:
  hosts:
  - "*"
  gateways:
  - hawk-app-gateway
  http:
  - match:
     - uri:
        prefix: "/auth"
    route:
    - destination: 
        host: keycloak.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logic-virutal-service
spec:
  hosts:
    - "runlogic-service.hawk.svc.cluster.local"
  http:
    - route:
        - destination:
            host: runlogic-service
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hawk-virutal-service
spec:
  hosts:
    - "hawk-server-service.hawk.svc.cluster.local"
  http:
    - route:
        - destination:
            host: hawk-server-service
            port:
              number: 8080
      match:
      - uri :
          prefix: "/hawk"
      rewrite:
        uri: "/"
      name: hawk-server-route