server:
  port: 8077

spring:
  application:
    name: logic
  cloud:
    config:
      uri: http://localhost:8081
#  cloud:
#    config:
#      uri: http://localhost:8081




client:
  name: nihil


#server:
#  port: 8070
#spring:
#  application:
#    name: logic
#  profiles:
#    active: dev
#  cloud:
#    config:
#  config:
#    uri: http://localhost:8081
#    import: