apiVersion: apps/v1
kind: Deployment
metadata:
  name: runlogic
  namespace: hawk
  labels:
    app: runlogic
    env: test
spec:
  selector:
    matchLabels:
      app: runlogic
      env: test
  template:
    metadata:
      labels:
        app: runlogic
        env: test
    spec:
      containers:
        - name: runlogic
          image: tibinlukose/runlogic:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: runlogic-service
  namespace: hawk
spec:
  selector:
    app: runlogic
    env: test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081